ville_id_nom = {
    "1": "Casablanca",
    "2": "Fès",
    "3": "Rabat",
    "4": "Marrakech",
    "5": "Tanger",
    "6": "Agadir",
    "7": "Meknès",
    "53": "Mohammedia",
    "8": "Oujda",
    "9": "Kenitra",
    "10": "Tétouan",
    "11": "Khouribga",
    "12": "Temara",
    "13": "Laâyoune",
    "14": "Safi",
    "15": "Beni Mellal",
    "16": "El Jadida",
    "17": "Taza",
    "18": "Nador",
    "19": "Settat",
    "20": "Ksar El Kebir",
    "21": "Larache",
    "22": "Khemisset",
    "23": "Tiznit",
    "24": "Berrechid",
    "25": "Oued Zem",
    "26": "Al Fqih Ben Çalah",
    "27": "Taourirt",
    "28": "Berkane",
    "29": "Sidi Slimane",
    "30": "Errachidia",
    "31": "Sidi Kacem",
    "32": "Khenifra",
    "33": "Tiflet",
    "34": "Essaouira",
    "35": "Taroudant",
    "36": "El Kelâa des Sraghna",
    "37": "Oulad Teima",
    "38": "Youssoufia",
    "39": "Sefrou",
    "40": "Ben Guerir",
    "41": "Tan-Tan",
    "42": "Ouazzane",
    "43": "Guercif",
    "44": "Ouarzazat",
    "45": "Al Hoceïma",
    "46": "Jerada",
    "47": "Chefchaouene",
    "48": "Fnidek",
    "49": "Ouled Nemma",
    "50": "Salé",
    "60": "Ifrane",
    "59": "Figuig (Centre)",
    "58": "Sidi Ifni",
    "57": "Asilah",
    "56": "Tarfaya",
    "55": "Goulmima",
    "54": "Azrou",
    "52": "Guelmim",
    "64": "Smara",
    "63": "Oulmes",
    "62": "Dakhla",
    "61": "Imlili",
    "147": "Boulemane",
    "149": "Taghazout",
    "153": "Moulay Yacoub",
    "164": "Azilal",
    "169": "Skhirate",
    "189": "Midelt",
    "191": "Inezgane",
    "244": "Tata",
    "215": "Tafraout",
    "231": "Kelaat Mgouna",
    "142": "Saidia",
    "140": "Sidi Harazem",
    "240": "Bouarfa",
    "85": "Taounate",
    "261": "Aoufous",
    "90": "Azemmour",
    "163": "Arfoud",
    "100": "Ahfir",
    "115": "Ouezzane",
    "259": "El Hajeb",
    "254": "Kasba Tadla",
    "262": "Zagora",
    "247": "Chichaoua",
    "199": "Bouznika",
    "124": "Guenfouda",
    "252": "Cap Negro II",
    "235": "Sidi Bennour",
    "214": "Tinghir",
    "97": "Oued Amlil",
    "130": "Mediouna",
    "122": "Tamanar",
    "120": "Zag",
    "89": "Bouskoura",
    "70": "Mellila"
}